#!/usr/bin/env python3
"""Generate procedural-city-data.js from city.json + usage.json.

Bridges the data-driven city (city.json) to the renderer (procedural-city-data.js).
Growth rules in city.json drive district size/tier based on real usage data.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CITY = ROOT / "city.json"
USAGE = ROOT / "usage.json"
OUT = ROOT / "procedural-city-data.js"


def load_data():
    return json.loads(CITY.read_text()), json.loads(USAGE.read_text()) if USAGE.exists() else {}


def get_provider_used(providers, source):
    for p in providers:
        if p.get("id") == source:
            return p.get("used", 0), p.get("status", "unknown")
    return 0, "no_key"


def apply_growth(projects, city, usage):
    growth = city.get("growth", {})
    triggers = growth.get("triggers", [])
    providers = usage.get("providers", [])
    for proj in projects:
        source = proj.get("source")
        if not source:
            continue
        used, status = get_provider_used(providers, source)
        proj["_used"] = used
        proj["_status"] = status
        for trig in triggers:
            if trig["district"] != proj["id"]:
                continue
            metric = trig.get("metric")
            threshold = trig.get("threshold")
            action = trig["action"]
            if metric is None or threshold is None:
                continue
            crossed = (metric == "tokens" and used >= threshold) or \
                      (metric == "usd" and used >= threshold) or \
                      (metric == "percent" and isinstance(used, (int, float)) and used >= threshold)
            if crossed:
                if action == "size_up":
                    factor = trig.get("factor", growth.get("expansionRate", 1.25))
                    proj["size"]["width"] *= factor
                    proj["size"]["depth"] *= factor
                    proj["_growth"] = trig.get("evidence", f"size_up: {metric}>={threshold}")
                elif action == "tier_up":
                    proj["tier"] = proj.get("tier", 0) + 1
                    proj["_growth"] = trig.get("evidence", f"tier_up: {metric}>={threshold}")
    return projects


def generate_js(projects):
    L = []
    a = L.append
    a('// procedural-city-data.js')
    a('// AUTO-GENERATED by generate-city-data.py — do not edit manually.')
    a('// Source: city.json + usage.json via growth rules.')
    a('')
    a('export const CITY_CONFIG = {')
    a('  seed: 1701, size: 34, terrainY: 0, roadInset: 1.6,')
    a('  parcelPadding: 0.55, maxRoadDepth: 3,')
    a('};')
    a('')
    a('export const PROJECTS = [')
    for p in projects:
        a('  {')
        a(f'    id: "{p["id"]}",')
        a(f'    name: "{p.get("name", p["id"])}",')
        a(f'    tokenShare: {p.get("tokenShare", 1)},')
        o = p.get("origin", {"x": 0, "z": 0})
        a(f'    origin: {{ x: {o["x"]}, z: {o["z"]} }},')
        s = p.get("size", {"width": 8, "depth": 8})
        a(f'    size: {{ width: {s["width"]}, depth: {s["depth"]} }},')
        a(f'    style: "{p.get("style", "civic")}",')
        a(f'    accent: "{p.get("accent", "ink")}",')
        if p.get("provider"):
            a(f'    provider: "{p["provider"]}",')
        if p.get("tier"):
            a(f'    tier: {p["tier"]},')
        if p.get("kind"):
            a(f'    kind: "{p["kind"]}",')
        if p.get("evidence"):
            a(f'    evidence: "{p["evidence"]}",')
        if p.get("_growth"):
            a(f'    _growth: "{p["_growth"]}",')
        if p.get("_used") is not None:
            a(f'    _used: {p["_used"]},')
        if p.get("_status"):
            a(f'    _status: "{p["_status"]}",')
        a('  },')
    a('];')
    a('')
    # Utility functions (from original)
    a('export function createRng(seed = CITY_CONFIG.seed) {')
    a('  let state = seed >>> 0;')
    a('  return {')
    a('    next() { state = (1664525 * state + 1013904223) >>> 0; return state / 4294967296; },')
    a('    float(min, max) { return min + (max - min) * this.next(); },')
    a('    int(min, max) { return Math.floor(this.float(min, max + 1)); },')
    a('    pick(list) { return list[this.int(0, list.length - 1)]; },')
    a('    fork(offset) { return createRng((state ^ offset) >>> 0); },')
    a('  };')
    a('}')
    a('')
    a('function id(prefix, index) {')
    a('  return `${prefix}_${String(index).padStart(3, "0")}`;')
    a('}')
    a('')
    a('function clamp01(value) { return Math.min(1, Math.max(0, value)); }')
    a('')
    a('function makeRect(x, z, width, depth) {')
    a('  return { minX: x - width / 2, maxX: x + width / 2, minZ: z - depth / 2, maxZ: z + depth / 2, width, depth };')
    a('}')
    a('')
    a('function createRoad({ kind, from, to, width, districtId, depth = 0 }) {')
    a('  return { id: `${districtId}_${kind}_${depth}_${Math.round(from.x * 10)}_${Math.round(to.z * 10)}`, kind, from, to, width, districtId, depth };')
    a('}')
    a('')
    a('export function generateRoadNetwork(projects = PROJECTS, config = CITY_CONFIG) {')
    a('  const roads = [];')
    a('  const bounds = config.size / 2 - config.roadInset;')
    a('  const major = 0.42; const minor = 0.2;')
    a('  roads.push(createRoad({ kind: "boulevard", from: { x: -bounds, z: 0 }, to: { x: bounds, z: 0 }, width: major, districtId: "city" }));')
    a('  roads.push(createRoad({ kind: "boulevard", from: { x: 0, z: -bounds }, to: { x: 0, z: bounds }, width: major, districtId: "city" }));')
    a('  roads.push(createRoad({ kind: "ring", from: { x: -8.6, z: -5.5 }, to: { x: 8.6, z: -5.5 }, width: minor, districtId: "city" }));')
    a('  roads.push(createRoad({ kind: "ring", from: { x: -8.6, z: 5.7 }, to: { x: 8.6, z: 5.7 }, width: minor, districtId: "city" }));')
    a('  roads.push(createRoad({ kind: "ring", from: { x: -5.7, z: -8.7 }, to: { x: -5.7, z: 8.7 }, width: minor, districtId: "city" }));')
    a('  roads.push(createRoad({ kind: "ring", from: { x: 5.7, z: -8.7 }, to: { x: 5.7, z: 8.7 }, width: minor, districtId: "city" }));')
    a('  projects.filter(p => p.id !== "core").forEach(project => {')
    a('    const district = makeRect(project.origin.x, project.origin.z, project.size.width, project.size.depth);')
    a('    const rng = createRng(config.seed + project.origin.x * 19 + project.origin.z * 31);')
    a('    const hc = project.tokenShare > 0.55 ? 2 : 1;')
    a('    const vc = project.tokenShare > 0.45 ? 2 : 1;')
    a('    for (let i = 1; i <= hc; i++) {')
    a('      const z = district.minZ + (i / (hc + 1)) * district.depth;')
    a('      roads.push(createRoad({ kind: "lane", from: { x: district.minX, z }, to: { x: district.maxX, z: z + rng.float(-0.25, 0.25) }, width: 0.14, districtId: project.id, depth: 1 }));')
    a('    }')
    a('    for (let i = 1; i <= vc; i++) {')
    a('      const x = district.minX + (i / (vc + 1)) * district.width;')
    a('      roads.push(createRoad({ kind: "lane", from: { x, z: district.minZ }, to: { x: x + rng.float(-0.25, 0.25), z: district.maxZ }, width: 0.14, districtId: project.id, depth: 1 }));')
    a('    }')
    a('  });')
    a('  // Session-driven roads: Hermes connects to districts based on which providers its sessions touched.')
    a('  const sessions = config.hermes_sessions;')
    a('  if (sessions) {')
    a('    const hermes = projects.find(p => p.id === "hermes");')
    a('    if (hermes) {')
    a('      const providerToDistrict = { "nous": "openrouter", "opencode-free": "opencode" };')
    a('      for (const [provider, count] of Object.entries(sessions)) {')
    a('        const targetId = providerToDistrict[provider];')
    a('        if (!targetId) continue;')
    a('        const target = projects.find(p => p.id === targetId);')
    a('        if (!target) continue;')
    a('        const width = count > 50 ? 0.35 : count >= 5 ? 0.2 : 0.1;')
    a('        roads.push(createRoad({')
    a('          kind: count > 50 ? "boulevard" : "lane",')
    a('          from: { x: hermes.origin.x, z: hermes.origin.z },')
    a('          to: { x: target.origin.x, z: target.origin.z },')
    a('          width, districtId: "hermes", depth: 0,')
    a('        }));')
    a('      }')
    a('    }')
    a('  }')
    a('  return roads;')
    a('}')
    a('')
    a('const STYLE_RULES = {')
    a('  civic: { minHeight: 1.2, maxHeight: 6.8, minFootprint: 1.8, maxFootprint: 3.2, density: 0.86, landmarkChance: 0.3 },')
    a('  laboratory: { minHeight: 0.8, maxHeight: 4.8, minFootprint: 1.2, maxFootprint: 2.7, density: 0.74, landmarkChance: 0.16 },')
    a('  residential: { minHeight: 0.7, maxHeight: 3.8, minFootprint: 0.9, maxFootprint: 2.0, density: 0.92, landmarkChance: 0.08 },')
    a('  archive: { minHeight: 0.6, maxHeight: 3.7, minFootprint: 1.0, maxFootprint: 2.4, density: 0.57, landmarkChance: 0.24 },')
    a('  industrial: { minHeight: 0.5, maxHeight: 3.2, minFootprint: 1.2, maxFootprint: 2.9, density: 0.6, landmarkChance: 0.1 },')
    a('};')
    a('')
    a('function makeParcel(project, index, rng) {')
    a('  const cols = project.size.width > 8 ? 3 : 2; const rows = project.size.depth > 7 ? 3 : 2;')
    a('  const col = index % cols; const row = Math.floor(index / cols);')
    a('  const cellWidth = project.size.width / cols; const cellDepth = project.size.depth / rows;')
    a('  const x = project.origin.x - project.size.width / 2 + cellWidth * (col + 0.5) + rng.float(-0.4, 0.4);')
    a('  const z = project.origin.z - project.size.depth / 2 + cellDepth * (row + 0.5) + rng.float(-0.4, 0.4);')
    a('  return makeRect(x, z, cellWidth - 0.7, cellDepth - 0.7);')
    a('}')
    a('')
    a('function createBuilding(project, parcel, index, rng) {')
    a('  const rules = STYLE_RULES[project.style];')
    a('  const completeness = clamp01(project.tokenShare);')
    a('  const isLandmark = rng.next() < rules.landmarkChance;')
    a('  const width = rng.float(rules.minFootprint, Math.min(rules.maxFootprint, parcel.width));')
    a('  const depth = rng.float(rules.minFootprint, Math.min(rules.maxFootprint, parcel.depth));')
    a('  const heightBias = isLandmark ? 1.35 : 1;')
    a('  const height = rng.float(rules.minHeight, rules.maxHeight) * heightBias;')
    a('  const builtFraction = clamp01(0.22 + completeness * 0.78 + rng.float(-0.13, 0.09));')
    a('  return {')
    a('    id: id(`${project.id}_building`, index), projectId: project.id,')
    a('    family: isLandmark ? (project.style === "archive" ? "dome" : "tower") : rng.pick(["block", "courtyard", "terrace"]),')
    a('    center: { x: parcel.minX + parcel.width / 2, z: parcel.minZ + parcel.depth / 2 },')
    a('    footprint: { width, depth }, height,')
    a('    levels: Math.max(1, Math.round(height / 0.45)), completeness: builtFraction,')
    a('    landmark: isLandmark, orientation: rng.float(-0.18, 0.18), detailDensity: 0.25 + completeness * 0.75,')
    a('  };')
    a('}')
    a('')
    a('function createTrees(project, rng, count) {')
    a('  const trees = [];')
    a('  for (let i = 0; i < count; i++) {')
    a('    trees.push({')
    a('      id: id(`${project.id}_tree`, i), projectId: project.id,')
    a('      position: { x: project.origin.x + rng.float(-project.size.width / 2, project.size.width / 2), z: project.origin.z + rng.float(-project.size.depth / 2, project.size.depth / 2) },')
    a('      height: rng.float(0.32, 0.82), canopy: rng.float(0.15, 0.36),')
    a('      completeness: clamp01(project.tokenShare + rng.float(-0.18, 0.12)),')
    a('    });')
    a('  } return trees;')
    a('}')
    a('')
    a('export function generateBuildingClusters(projects = PROJECTS, config = CITY_CONFIG) {')
    a('  const districts = [];')
    a('  projects.forEach((project, idx) => {')
    a('    const rng = createRng(config.seed + idx * 997);')
    a('    const rules = STYLE_RULES[project.style];')
    a('    const parcelCount = project.id === "core" ? 12 : 5 + Math.round(project.tokenShare * 8);')
    a('    const parcels = []; const buildings = [];')
    a('    for (let i = 0; i < parcelCount; i++) {')
    a('      const parcel = makeParcel(project, i, rng); parcels.push({ id: id(`${project.id}_parcel`, i), ...parcel });')
    a('      if (rng.next() <= rules.density || project.id === "core") buildings.push(createBuilding(project, parcel, buildings.length, rng));')
    a('    }')
    a('    const treeCount = project.id === "industrial" ? 4 : Math.round(4 + project.tokenShare * 18);')
    a('    districts.push({ id: project.id, project, parcels, buildings, trees: createTrees(project, rng, treeCount), completeness: clamp01(project.tokenShare) });')
    a('  }); return districts;')
    a('}')
    a('')
    a('export function fitConfig(projects = PROJECTS, config = CITY_CONFIG) {')
    a('  let reach = 0;')
    a('  for (const project of projects) {')
    a('    const hw = (project.size?.width ?? 6) / 2; const hd = (project.size?.depth ?? 6) / 2;')
    a('    reach = Math.max(reach, Math.abs(project.origin?.x ?? 0) + hw, Math.abs(project.origin?.z ?? 0) + hd);')
    a('  }')
    a('  if (!reach) return config;')
    a('  const size = Math.max(config.size, Math.ceil((reach + 2.8) * 2) / 2);')
    a('  return size === config.size ? config : { ...config, size, grew: true };')
    a('}')
    a('')
    a('export function generateCityData({ projects = PROJECTS, config = CITY_CONFIG } = {}) {')
    a('  const fitted = fitConfig(projects, config);')
    a('  return { config: fitted, projects, roads: generateRoadNetwork(projects, fitted), districts: generateBuildingClusters(projects, fitted) };')
    a('}')
    a('')
    return '\n'.join(L)


def main():
    city, usage = load_data()
    projects = apply_growth(list(city.get("projects", [])), city, usage)
    js = generate_js(projects)
    OUT.write_text(js)
    print(f"Generated {OUT} ({len(js)} bytes)")
    for p in projects:
        if p.get("_growth"):
            print(f"  GROWTH: {p['id']} — {p['_growth']}")


if __name__ == "__main__":
    main()
